/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
export module ui.test {
    export class AstarUI extends Laya.View {
		public container:Laya.Box;
		public starBtn:Laya.Button;
		public endBtn:Laya.Button;
		public searchBtn:Laya.Button;
        public static  uiView:any ={"type":"View","props":{"width":1136,"height":640},"compId":2,"child":[{"type":"Box","props":{"var":"container","top":0,"right":0,"left":0,"bottom":0},"compId":4},{"type":"Button","props":{"y":70,"x":350,"var":"starBtn","skin":"comp/button.png","label":"start"},"compId":6},{"type":"Button","props":{"y":70,"x":482,"var":"endBtn","skin":"comp/button.png","label":"endBtn"},"compId":7},{"type":"Button","props":{"y":70,"x":603,"var":"searchBtn","skin":"comp/button.png","label":"search"},"compId":8}],"loadList":["comp/button.png"],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(AstarUI.uiView);
        }
    }
    export class TestSceneUI extends Laya.Scene {
		public scoreLbl:Laya.Label;
		public tipLbll:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/TestScene");
        }
    }
    export class ViewTestUI extends Laya.View {
		public A1:Laya.Radio;
		public A2:Laya.Radio;
		public A3:Laya.Radio;
		public B1:Laya.Radio;
		public B2:Laya.Radio;
        public static  uiView:any ={"type":"View","props":{"width":1136,"height":640},"compId":2,"child":[{"type":"Radio","props":{"y":126,"x":170,"var":"A1","skin":"comp/radio.png","label":"A1"},"compId":8},{"type":"Radio","props":{"y":154,"x":170,"var":"A2","skin":"comp/radio.png","label":"A2"},"compId":9},{"type":"Radio","props":{"y":190,"x":170,"var":"A3","skin":"comp/radio.png","label":"A3"},"compId":10},{"type":"Radio","props":{"y":126,"x":233,"var":"B1","skin":"comp/radio.png","label":"B1"},"compId":11},{"type":"Radio","props":{"y":154,"x":233,"var":"B2","skin":"comp/radio.png","label":"B2"},"compId":13}],"loadList":["comp/radio.png"],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(ViewTestUI.uiView);
        }
    }
}